
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  data:
    mongodb:
      host: mongodb://127.0.0.1:27017
      port: 27017
      database: test
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.74.128:3306/myDB
    username: web_user2
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true
     
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 546671564624-1ifo34gjghp8m0lqrcajre7fdhctu5kp.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile



          naver:
             client-id: vPQ0o6THA5u9n1q1RhBH
             client-secret: xo_8akH3pj
             scope:
             - name
             - email
             client-name: Naver
             authorization-grant-type: authorization_code
             redirect-uri: http://localhost:8000/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌





  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234